/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CZsEncrypt */

#ifndef _Included_CZsEncrypt
#define _Included_CZsEncrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CZsEncrypt
 * Method:    d
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_CZsEncrypt_d(JNIEnv * env, jclass clazz, jbyteArray byarray, jint offset,jint len);

/*
 * Class:     CZsEncrypt
 * Method:    e
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_CZsEncrypt_e(JNIEnv * env, jclass clazz, jbyteArray byarray, jint offset,jint len);

#ifdef __cplusplus
}
#endif
#endif
